# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('texto_mkt', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={},
        ),
    ]
