# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_produtos', '0002_auto_20180701_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos2',
        ),
    ]
